version: '3.1'

services:
  mysql:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: product      # 데이터베이스 이름
      MYSQL_USER: impati              # 데이터베이스 사용자
      MYSQL_PASSWORD: impati       # 사용자 비밀번호
      MYSQL_ROOT_PASSWORD: 123  # 루트 비밀번호
    ports:
      - '3306:3306'  # 포트 매핑 (호스트:컨테이너)
