spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: impati
    password: impati
    jdbcUrl: jdbc:mysql://localhost:3306/product
