spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: impati
    password: impati
    jdbcUrl: jdbc:mysql://localhost:3306/product
  flyway:
    enabled: false
